export const cityOptions = [
  { value: 'Banda Aceh', label: 'Banda Aceh' },
  { value: 'Bandar Lampung', label: 'Bandar Lampung' },
  { value: 'Bandung', label: 'Bandung' },
  { value: 'Banjar', label: 'Banjar' },
  { value: 'Batam', label: 'Batam' },
  { value: 'Batu', label: 'Batu' },
  { value: 'Bekasi', label: 'Bekasi' },
  { value: 'Bengkulu', label: 'Bengkulu' },
  { value: 'Bima', label: 'Bima' },
  { value: 'Binjai', label: 'Binjai' },
  { value: 'Blitar', label: 'Blitar' },
  { value: 'Bogor', label: 'Bogor' },
  { value: 'Bukittinggi', label: 'Bukittinggi' },
  { value: 'Cilegon', label: 'Cilegon' },
  { value: 'Cimahi', label: 'Cimahi' },
  { value: 'Cirebon', label: 'Cirebon' },
  { value: 'Denpasar', label: 'Denpasar' },
  { value: 'Depok', label: 'Depok' },
  { value: 'Dumai', label: 'Dumai' },
  { value: 'Gunungsitoli', label: 'Gunungsitoli' },
  { value: 'Jakarta Barat', label: 'Jakarta Barat' },
  { value: 'Jakarta Pusat', label: 'Jakarta Pusat' },
  { value: 'Jakarta Selatan', label: 'Jakarta Selatan' },
  { value: 'Jakarta Timur', label: 'Jakarta Timur' },
  { value: 'Jakarta Utara', label: 'Jakarta Utara' },
  { value: 'Jambi', label: 'Jambi' },
  { value: 'Kediri', label: 'Kediri' },
  { value: 'Kupang', label: 'Kupang' },
  { value: 'Langsa', label: 'Langsa' },
  { value: 'Lhokseumawe', label: 'Lhokseumawe' },
  { value: 'Lubuklinggau', label: 'Lubuklinggau' },
  { value: 'Madiun', label: 'Madiun' },
  { value: 'Magelang', label: 'Magelang' },
  { value: 'Malang', label: 'Malang' },
  { value: 'Mataram', label: 'Mataram' },
  { value: 'Medan', label: 'Medan' },
  { value: 'Metro', label: 'Metro' },
  { value: 'Mojokerto', label: 'Mojokerto' },
  { value: 'Padang', label: 'Padang' },
  { value: 'Padang Panjang', label: 'Padang Panjang' },
  { value: 'Padangsidimpuan', label: 'Padangsidimpuan' },
  { value: 'Pagar Alam', label: 'Pagar Alam' },
  { value: 'Palembang', label: 'Palembang' },
  { value: 'Pangkal Pinang', label: 'Pangkal Pinang' },
  { value: 'Pariaman', label: 'Pariaman' },
  { value: 'Pasuruan', label: 'Pasuruan' },
  { value: 'Payakumbuh', label: 'Payakumbuh' },
  { value: 'Pekalongan', label: 'Pekalongan' },
  { value: 'Pekanbaru', label: 'Pekanbaru' },
  { value: 'Pematang Siantar', label: 'Pematang Siantar' },
  { value: 'Pontianak', label: 'Pontianak' },
  { value: 'Prabumulih', label: 'Prabumulih' },
  { value: 'Probolinggo', label: 'Probolinggo' },
  { value: 'Sabang', label: 'Sabang' },
  { value: 'Salatiga', label: 'Salatiga' },
  { value: 'Sawah Lunto', label: 'Sawah Lunto' },
  { value: 'Semarang', label: 'Semarang' },
  { value: 'Serang', label: 'Serang' },
  { value: 'Sibolga', label: 'Sibolga' },
  { value: 'Singkawang', label: 'Singkawang' },
  { value: 'Solok', label: 'Solok' },
  { value: 'Subulussalam', label: 'Subulussalam' },
  { value: 'Sukabumi', label: 'Sukabumi' },
  { value: 'Sungai Penuh', label: 'Sungai Penuh' },
  { value: 'Surabaya', label: 'Surabaya' },
  { value: 'Surakarta', label: 'Surakarta' },
  { value: 'Tangerang', label: 'Tangerang' },
  { value: 'Tangerang Selatan', label: 'Tangerang Selatan' },
  { value: 'Tanjung Balai', label: 'Tanjung Balai' },
  { value: 'Tanjung Pinang', label: 'Tanjung Pinang' },
  { value: 'Tasikmalaya', label: 'Tasikmalaya' },
  { value: 'Tebing Tinggi', label: 'Tebing Tinggi' },
  { value: 'Tegal', label: 'Tegal' },
  { value: 'Yogyakarta', label: 'Yogyakarta' },
];
